{{- if not .Values.rollout.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go.fullname" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go.selectorLabels" . | nindent 6 }}
  template:
    {{- include "go.podTemplateSpec" . | nindent 4 }}
{{- end }}
