{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "go.externalSecretTargetName" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ include "go.secretStoreRefName" . }}
    kind: {{ include "go.secretStoreRefKind" . }}
  target:
    name: {{ include "go.externalSecretTargetName" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | default "Owner" }}
    {{- with .Values.externalSecret.target.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
