{{- if and .Values.externalSecret.enabled .Values.externalSecret.secretStore.create .Values.externalSecret.secretStore.provider }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.externalSecret.secretStore.kind | default "SecretStore" }}
metadata:
  name: {{ include "go.secretStoreName" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.externalSecret.secretStore.provider | nindent 4 }}
{{- end }}
