{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go.fullname" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  {{- if and .Values.metrics.enabled .Values.metrics.serviceAnnotations.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ include "go.metrics.port" . | quote }}
    prometheus.io/path: {{ .Values.metrics.path }}
    prometheus.io/scheme: {{ .Values.metrics.scheme }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "go.selectorLabels" . | nindent 4 }}
{{- end }}
